name: time
main: me.LorenzoKyne.time.TestTime
author: LorenzoKyne
version: 1.0
description: Plugin di test del conteggio del tempo.
commands:
  time:
    description: Shows the time passed from the start of the server.
    usage: /<command>
  totaltime:
    description: Shows the total time passed from the start of the server in seconds.
    usage: /<command>